name: Infra health check (prod)
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
  push:
    branches:
      - 'prod'
  pull_request:
    branches:
      - 'prod'

env:
  AWS_REGION: eu-west-3

jobs:
  check-sync-stack:
    timeout-minutes: 300
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Configure prod AWS credentials
        if: ${{ github.ref_name == 'prod' }}
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: GET /dummy-table
        run: |
          export API_URL_SSM="`aws ssm get-parameter --name /poja-prime/${{ github.ref_name }}/api/url`"
          sudo apt-get install jq
          export API_URL=`echo $API_URL_SSM | jq -r '.Parameter.Value'`
          curl --fail "$API_URL"/dummy-table

  check-async-stack:
    timeout-minutes: 300
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Configure prod AWS credentials
        if: ${{ github.ref_name == 'prod' }}
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: GET /uuid-created
        run: |
          PARAMETER_NAME="/poja-prime/prod/api/url"

          API_URL_SSM=$(aws ssm get-parameter --name $PARAMETER_NAME --query Parameter.Value --with-decryption --output text 2>/dev/null)

          if [ $? -eq 0 ]; then
            if [ -n "$API_URL_SSM" ]; then
              sudo apt-get install -y jq

              API_URL=$(echo "$API_URL_SSM" | jq -r '.' 2>/dev/null)

              if [ -n "$API_URL" ]; then
                curl --max-time 60 --fail "$API_URL"/uuid-created

                if [ $? -ne 0 ]; then
                  echo "Failed to perform curl request."
                  exit 1
                fi
              else
                echo "Failed to extract API_URL from the SSM parameter value."
                exit 1
              fi
            else
              echo "SSM parameter $PARAMETER_NAME has an empty value."
              exit 1
            fi
          else
            echo "Failed to retrieve SSM parameter $PARAMETER_NAME."
            exit 1
          fi
